name: Only accept pulling request into staging branch via specific user

permissions:
  pull-requests: write
  issues: write

on:
  workflow_call:
  pull_request:
    branches:
      - 'staging'
      - 'release/OAM-[0-9]+'
jobs:
    call-reusable:
      uses: https://github.com/phtrungorg/test-app/.github/workflows/pr-control.yml@main
